# Generated by Django 4.0.6 on 2022-07-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0004_alter_perfil_pot_alter_perfil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cor',
            new_name='cor_favorita',
        ),
    ]
