# Generated by Django 4.0.6 on 2022-07-14 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0004_alter_perfil_pot_alter_perfil_user'),
        ('POT', '0001_initial'),
        ('Reuniao', '0002_reuniao_pot_reuniao_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='POT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_do_pot', to='POT.pot'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='participantes',
            field=models.ManyToManyField(related_name='reunioes_do_perfil', to='Perfil.perfil'),
        ),
    ]
